# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=ABC123
language: "php"

php:
  - 8.0.1

before_script:
  - composer update
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - XDEBUG_MODE=coverage composer exec --verbose phpunit tests -- --coverage-text
  - XDEBUG_MODE=coverage composer exec --verbose phpunit tests -- --coverage-clover build/logs/clover.xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT