name: Linter

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: uploud_repo
      uses: actions/checkout@v2

    - name: composer_install
      run: composer install

    - name: make_lint
      run: make lint

    - name: make_test
      run: make test

    # Add Code Climate secret key
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE }}
    with:
      coverageCommand: make test-coverage
      coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
      debug: true
