name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: uploud_repo
      uses: actions/checkout@v2

    - name: composer_install
      run: composer install --dev
    
    - name: install_xdebug 
      run: pecl install xdebug

    - name: test2
      run: echo xdebug.mode = coverage >> /usr/local/etc/php/8.0/php.ini

    - name: make_lint
      run: make lint

    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ac5c43bd7e74410896d36d0ea8683eb3
      with:
        coverageCommand: composer exec --verbose phpunit tests -- --coverage-text
        coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
        debug: true
